

install:
	if [ ! -e /usr/local/share/touchmegames/images/progressImages ]; \
		then mkdir /usr/local/share/touchmegames/images/progressImages; \
	fi
	
	cp *.* /usr/local/share/touchmegames/images/progressImages; \
